Repository khulnasoft/ThreatPot, pull requests merged in 2024-10, with the labels that each got.

#2 CyberPot fix
  README.md
  api/serializers.py
  api/views.py
  authentication/serializers.py
  authentication/views.py
  tests/test_serializers.py
  tests/test_views.py
  threatpot/cronjobs/monitor_honeypots.py
Labels: documentation, Bug fix, Review effort [1-5]: 1

#19 Develop
  .deepsource.toml
  frontend/package-lock.json
  frontend/package.json
Labels: Review effort [1-5]: 2

#20 Develop
  docker/Dockerfile
  docker/Dockerfile_nginx
  frontend/package-lock.json
  frontend/package.json
  requirements/project-requirements.txt
Labels: Review effort [1-5]: 3
